PULL_REQUEST_TEMPLATE: pass --installed to brew
On a `--new` formula, after successful local `brew install`,  `brew audit --new formula_or_formula_filename` will otherwise fail due to the formula not being available from a cask, and, to quote,

```
$ brew audit --new rpds-py.rb
Error: Calling brew audit [path ...] is disabled! Use brew audit [name ...] instead.
Please report this issue:
  https://docs.brew.sh/Troubleshooting

$ brew audit --new rpds-py
Error: These formulae are not in any locally installed taps!

  rpds-py

You may need to run `brew tap` to install additional taps.
```